name: Git Analyze CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip and wheel
        run: python -m pip install --upgrade pip wheel

      - name: Install git-analyzer (from source)
        run: pip install .

      - name: Run git-analyze summary
        run: git-analyze summary

      - name: Run git-analyze log
        run: git-analyze log

      - name: Archive daily devlog
        uses: actions/upload-artifact@v4
        with:
          name: devlog
          path: devlog-*.md
          if-no-files-found: ignore
